### ISSUE TITLE
graph define problem with the code

### ISSUE THREAD

**Issue by guoyinwang** [dsv77/hashembedding#1]
Hi, 

I am trying to try this interesting work. But when I try to run the example.py, I got the following problem:

When setting the hash embedding False:
"""
Using TensorFlow backend.
/home/guoyin/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py:559: UserWarning: Class `layers.ReduceSum` defines `get_output_shape_for` but does not override `compute_output_shape`. If this is a Keras 1 layer, please implement `compute_output_shape` to support Keras 2.
  output_shape = self.compute_output_shape(input_shape)
example.py:21: UserWarning: Update your `Model` call to the Keras 2 API: `Model(inputs=Tensor("in..., outputs=Tensor("ac...)`
  model = Model(input=input_words, output=x)
Num parameters in model: 1001254
example.py:66: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  callbacks=[EarlyStopping(patience=5)])
Traceback (most recent call last):
  File "example.py", line 66, in <module>
    callbacks=[EarlyStopping(patience=5)])
  File "/home/guoyin/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1405, in fit
    batch_size=batch_size)
  File "/home/guoyin/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1299, in _standardize_user_data
    exception_prefix='model target')
  File "/home/guoyin/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 121, in _standardize_input_data
    str(array.shape))
ValueError: Error when checking model target: expected activation_1 to have 3 dimensions, but got array with shape (1128, 1)
"""

When set hash embedding True:
"""
Using TensorFlow backend.
Traceback (most recent call last):
  File "example.py", line 59, in <module>
    model = get_model(embedding, num_classes)
  File "example.py", line 14, in get_model
    x = embedding(input_words)
  File "/home/guoyin/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 554, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/guoyin/HashEmbedding/hashembedding/HashEmbedding/layers.py", line 86, in call
    p = K.expand_dims(p_0,dim=-1)
TypeError: expand_dims() got an unexpected keyword argument 'dim'
"""

Is there any small error of the code? 

Thanks

**Comment by guoyinwang** [comment]
I am also not sure if these problems caused by different package versions. I think it is better to provide working python/package versions.

Thanks,
Guoyin

**Comment by dsv77** [comment]
I think this is caused by package issues as you suggest. Keras version < 2.0 is quite different from Keras version > 2.0. I have added a requirements.txt file and tested on an empty Anaconda 3 environment.

**Comment by guoyinwang** [comment]
Thanks, changing to keras 1, then  the code works fine
